title:             DKe2's Developement Journal
email:             widoint@gmail.com
description:       A note for javascript, HTML5, develop culture
author:            Dekay Kim
url:               "http://dekaykim.github.io"
baseurl:           ""

# Social Profiles
github_username:   DekayKim
facebook_username: Duk Hyun Kim

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
