# Site settings
title: DKe2 Blog
SEOTitle: DKe2 Blog
header-img: img/home-bg.jpg
email: widoint@gmail.com
description: "개발 아카이브 | Developement Archive"
keyword: "Javascript, ES5, HTML5, WebGL"
url: "https://dekaykim.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
remote_theme : Huxpro/huxpro.github.io

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    DekayKim
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

